### PR TITLE
Starlite v2

### PR DESCRIPTION
**Pull request by peterschutt**
### Pull Request Checklist

[//]: # "Please review the [Starlite contribution guidelines](https://github.com/starlite-api/starlite/blob/main/CONTRIBUTING.rst) for this repository."

- [ ] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR

By submitting this issue, you agree to: 
- follow Starlite's [Code of Conduct](https://github.com/starlite-api/.github/blob/main/CODE_OF_CONDUCT.md)
- follow Starlite's [Contribution Guidelines](https://starliteproject.dev/community/contribution-guide)

### Description

[//]: # "Please describe your pull request for new release changelog purposes"

### Close Issue(s)

[//]: # "Please add in issue numbers this pull request will close, if applicable"
[//]: # "Examples: Fixes #4321 or Closes #1234"

### CODE REVIEW

**Comment by v3ss0n** [comment]
thanks for the relationship example , i am going to rebase scrumlog on this today.

**Comment by peterschutt** [comment]
> thanks for the relationship example , i am going to rebase scrumlog on this today.

That's great, thanks! Also see https://github.com/litestar-org/litestar/blob/dto-factory/tests/contrib/sqlalchemy/test_dto.py for more examples (especially the full module examples toward the bottom).

**Comment by v3ss0n** [comment]
OpenAPI won't get generated ( not ready currently? )

**Comment by v3ss0n** [comment]
cool , gonna test it out.

**Pull request closed without merging**
